# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QRf7t+SfzGgzFcEHYJhTY76nlUMITpZ+WlhmO/0dL/rgk2Q26JUGiGr78zU8HyMdXQ6REgZlF7aUYT3uvYozS/HTZoCugcy9tGeC3cllRAN54IFMMbPE09jiq3RqR6xEZNAbC4alcaA1FvtrGMoygO7DSf1vLpJ/qcvjsDXipRXmTLZHpTbQorqzBz+8kdwAbCpFzbEJ8AgxWjhZwGjJvh2PiEheJ+yXi+Bv9B3d0yxo80MUNCdy0H5k4hlHqJwSzsUqZQOPIbSRvBf5Mnbi6Ro67FU1hStxNIsle/RasCznGgHxdmQTNRMy3K/iJnc9G7O1f76Z9JyOWb923c1I+VpErowkg7RWNzw0enCQmTfQOkwXYZ3NanENj4EJjRUk4XahE3bMyeLxuVwoShhEzbvmyLdb9MXbngqW3HQSfQMeGXoUy/T47pg9+SbVgcbD5WriVXwqEvJAwTg7Xp+s0K/L/eurbKMigzTpv9Ne/ThfO3QCKs4ByKk8gtFYFqVKLHUvNqqmbmWsnTGzSyYtGavsbFempgBHnTW1r7z4VftmrwKL8hcSkauhT7m0H5IL73VKbt0XN7R5+5t6al8S2jn2V16+0GsxnvG6jyuxrqalQGGPCMlwt8pAkDmcGOUGtI11EipQwBgNgQfo7oXi3NzFLpHF62sJovg18R8jQuE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
