travis:
  secure:
    BINSTAR_TOKEN: oNL4m76xFXHZMUm2BtFPVVczXhEN62wqAt/+PRTFlDLnPPiK2aqYayhqZw7fkY8DXrtOOd+JwW4euf8x8IfMRV57dyDRPJ8muM7yA/vPrXen/uUThqALEqmJoLV95SZ+1xUVI2Bpt+zmA5wz1N9ASeU1mdl9l2IUadLvcl6+ZqPOWBrDrQAECYQVcuw1P4uSHIkETd6meiuM+KI2e8VeYq5MC/GTsnNET4DUiPlr3YbcQTMmJftMttXZrL+WDUQJc8cAYtlvjEPW3Pwb1lz8xZl2L7qTUNEmQcWEzRjojLsbmo35/uhd5lN2HhFtOS8rxrBtDrGTjRgQnLhWJQztD7JaAKIgktRf0u/PpKSrAVnTXY9nJI7MzQxYV26OK8DODk6v8EKtZQ3a+Lyc8F7i/D1sE6eh9imnqFksAjCECQE8fGDwIGT6STx0N0FSKnk8FAuCOtJ1suj4DP02wdtHdgArAFC5lERI98y3ap6ifijLac0YLw7dpeG0xmi0VSZPv68xNPvRWexmHmFi9YP92UpNqK8v9DGb0IRqJcMku/6dRIs6L1gm4bW6GY/LeQVwpG4cTAg8ZF+SPvYkNPXuJvneeoQeW4Hk2hX2ZCxNDHj3J8MiaQzF4z5YCCp2AZK0pX8Ztqe13KS/FYkw2cbRn+rx8ny6a2OEtyUagDqrmcs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
