travis:
  secure:
    BINSTAR_TOKEN: qa31YMgeNA+7ntO2c67KQfxTeFlaD00YxpuW8uaw9An0L1tK9nfznP+ePicorRn7o0sRCWr8Wjq7LBGtuKv47m+oe4z2W+jQuQe3ZqH5L+kNz3P7hE9/FQEh/zDitCB6uoXTR6H+D/UKJcpiiJ3Wiv6z6FVZpXnOVpppnINDgwBGuwgFj95jO2jAe2+49Ody9akT/OZBu7rlOqfmV23wqj2VDRMs+E5FW9jf587Wa9m4vhx4naZXKecToxop30rvN56R4mRevLoRBJDVPwl/jLGgIfZMXE2L28Sy9EPVYKGTY/8hJsdVnKBveQqfpYZYQiDjTbEm7MVWzQnLR0zTWYnzWp/ZXgP8oAjlc+wVnW9tyWhcShwlTh20kn6BgVg5dAgC7Nddlhjf5wNaHOoA/y+Ilop0Mr4T9G7b2gPlJSPiXm0VZ2/mYjx8s/kc/8puyC6eix3MUHLQXIjb2LCAlf7A4fqKl83asjhQbIgzhtE1CTtOY64eaUiVSsj9WZb5nFy6euqOTOMerdRmcucfSPFAtD2lC7W5sbYDccucVJaSap+mNnbRkccMT0uJR5XbvyMIU43ahL94NqdIid63dgqYaxQIPrsOiuPg6f5RXl3MBdbLH8/LWLgwcDBXQfvZwakBamSuq1bU+K5PAZDUlnfKkf+X60/d2a0tYDIOo64=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
